<a href="https://colab.research.google.com/github/Shikher-jain/Data_Science/blob/main/DL/PYTORCH/CampusX_PT/Pytorch_CampusX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1515]:
import torch

In [1516]:
print(torch.__version__)

2.11.0+cpu

In [1517]:
print(torch.cuda.is_available())

False

In [1518]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("No GPU available")

No GPU available

In [1519]:
torch.empty(2, 3)

tensor([[-1.4368e+20,  4.4111e-41, -1.4362e+20],
        [ 4.4111e-41, -1.4365e+20,  4.4111e-41]])

In [1520]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [1521]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [1522]:
torch.rand(2, 3)

tensor([[0.4114, 0.9021, 0.3660],
        [0.1300, 0.1422, 0.5999]])

In [1523]:
torch.manual_seed(101)
torch.rand(2, 3)

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])

In [1524]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [1525]:
print(torch.arange(1,11,2))
print(torch.linspace(1,10,4))
print(torch.eye(6))
print(torch.full((2,3),2.4))

tensor([1, 3, 5, 7, 9])
tensor([ 1.,  4.,  7., 10.])
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])
tensor([[2.4000, 2.4000, 2.4000],
        [2.4000, 2.4000, 2.4000]])

In [1526]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [1527]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [1528]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [1529]:
y = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
y.shape,y.dtype

(torch.Size([2, 3]), torch.float64)

In [1530]:
y.to((torch.int32))
x.dtype,y.dtype

(torch.int64, torch.float64)

In [1531]:
x.dtype,y.dtype

(torch.int64, torch.float64)

In [1532]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.2764, 0.4473, 0.8208],
        [0.6668, 0.1196, 0.7218]], dtype=torch.float64)

In [1533]:
torch.cat((x,x,x), dim=0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])

In [1534]:
print("X :" ,x)
print("Y :" ,y)

print("ADD")
print(x+y)
print(torch.add(x,y))
print(x.add(y))

print("SUBTRACT")
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

print("MULTIPLY")
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

print("DIVIDE")
print(x/y)
print(torch.div(x,y))
print(x.div(y))

print("POWER")
print(x**y)
print(torch.pow(x,y))
print(x.pow(y))

print("SQRT")
print(torch.sqrt(x))
print(x.sqrt())

print("EXP")
print(torch.exp(x))
print(x.exp())

print("LOG")
print(torch.log(x))
print(x.log())

print("SIN")
print(torch.sin(x))
print(x.sin())

print("COS")
print(torch.cos(x))
print(x.cos())

print("TAN")
print(torch.tan(x))
print(x.tan())

print("ABS")
print(torch.abs(x))
print(x.abs())

print("SUM")
print(torch.sum(x))
print(x.sum())

print("MEAN")
print(torch.mean(y))
print(y.mean())

print("MAX")
print(torch.max(x))
print(x.max())

print("MIN")
print(torch.min(x))
print(x.min())

print("ARGMAX")
print(torch.argmax(x))
print(x.argmax())

print("ARGMIN")
print(torch.argmin(x))
print(x.argmin())

print("EQUAL")
print(torch.eq(x,y))
print(x.eq(y))

print("NOT EQUAL")
print(torch.ne(x,y))
print(x.ne(y))

print("Std")
print(torch.std(y))
print(y.std())

print("Var")
print(torch.var(y))
print(y.var())

print("Transpose")
print(torch.t(x))
print(x.t())

print("Transpose")
print(torch.transpose(x,0,1))
print(x.transpose(0,1))

print("Reshape")
print(torch.reshape(x,(3,2)))
print(x.reshape(3,2))

print("Reshape")
print(torch.reshape(x,(6,1)))
print(x.reshape(6,1))

print("Reshape")
print(torch.reshape(x,(1,6)))
print(x.reshape(1,6))


print('dot')
print(torch.dot(x[0],x[1]))
print(x[0].dot(x[1]))

X : tensor([[1, 2, 3],
        [4, 5, 6]])
Y : tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
ADD
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
SUBTRACT
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
MULTIPLY
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], dtype=torch.float64)
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], dtype=torch.float64)
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], dtype=torch.float64)
DIVIDE
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
POWER
tensor([[1.0000e+00, 4.0000e+00, 2.7000e+01],
        [2.5600e+02, 3.1250e+03, 4.6656e+04]], dtype=torch.float64)
tensor([[1.0000e+00, 4.0000e+00, 2.7000e+01],
        [2.5600e+02, 3.1250e+03, 4.6656e+04]], dtype=torch.float64)
tensor([[1.0000e+00, 4.0000e+00, 2.7000e+01],
        [2.5600e+02, 3.1250e+03, 4.6656e+04]], dtype=torch.float64)
SQRT
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
EXP
tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])
tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])
LOG
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
SIN
tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794]])
tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794]])
COS
tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.6536,  0.2837,  0.9602]])
tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.6536,  0.2837,  0.9602]])
TAN
tensor([[ 1.5574, -2.1850, -0.1425],
        [ 1.1578, -3.3805, -0.2910]])
tensor([[ 1.5574, -2.1850, -0.1425],
        [ 1.1578, -3.3805, -0.2910]])
ABS
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
SUM
tensor(21)
tensor(21)
MEAN
tensor(3.5000, dtype=torch.float64)
tensor(3.5000, dtype=torch.float64)
MAX
tensor(6)
tensor(6)
MIN
tensor(1)
tensor(1)
ARGMAX
tensor(5)
tensor(5)
ARGMIN
tensor(0)
tensor(0)
EQUAL
tensor([[True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True]])
NOT EQUAL
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
Std
tensor(1.8708, dtype=torch.float64)
tensor(1.8708, dtype=torch.float64)
Var
tensor(3.5000, dtype=torch.float64)
tensor(3.5000, dtype=torch.float64)
Transpose
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Transpose
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Reshape
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Reshape
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
Reshape
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
dot
tensor(32)
tensor(32)

In [1535]:
print("Sigmoid")
x,torch.sigmoid(x)

Sigmoid

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[0.7311, 0.8808, 0.9526],
         [0.9820, 0.9933, 0.9975]]))

In [1536]:
print("ReLU")
x,torch.relu(x)

ReLU

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [1537]:
print("Softmax")
x =x.to(torch.float64)
x, torch.softmax(x, dim=0), torch.softmax(x, dim=1)

Softmax

(tensor([[1., 2., 3.],
         [4., 5., 6.]], dtype=torch.float64),
 tensor([[0.0474, 0.0474, 0.0474],
         [0.9526, 0.9526, 0.9526]], dtype=torch.float64),
 tensor([[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]], dtype=torch.float64))

# ====================

In [1538]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y.backward()
x.grad
x , y

(tensor(3., requires_grad=True), tensor(9., grad_fn=<PowBackward0>))

In [1539]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
z = torch.sin(y)
# y.backward()
z.backward()
x.grad, y.grad, z.grad
# x , y , z

/tmp/ipykernel_547/2126039507.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  x.grad, y.grad, z.grad

(tensor(-5.4668), None, None)

# ================

In [1540]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [1541]:
w,y,w,b

(tensor(1., requires_grad=True),
 tensor(0.),
 tensor(1., requires_grad=True),
 tensor(0., requires_grad=True))

In [1542]:
z = w*x+b
y_pred = torch.sigmoid(z)
loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred))

In [1543]:
z,y_pred,loss

(tensor(6.7000, grad_fn=<AddBackward0>),
 tensor(0.9988, grad_fn=<SigmoidBackward0>),
 tensor(6.7012, grad_fn=<NegBackward0>))

In [1544]:
loss.backward()

In [1545]:
w.grad, b.grad

(tensor(6.6918), tensor(0.9988))

# ===============

In [1546]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
y = x**2
# y.backward()
x.grad

In [1547]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
y1 = (x**2).mean()
y1.backward()
x.grad,x.grad.zero_

(tensor([0.6667, 1.3333, 2.0000]), <function Tensor.zero_>)

# =======training pipeline

In [1548]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [1549]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [1550]:
df.shape

(569, 33)

In [1551]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [1552]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [1553]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [1554]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [1555]:
X_train

array([[-0.80982937, -1.45747474, -0.77286548, ...,  0.25604036,
         0.65029577,  0.39307378],
       [ 0.96032171,  1.21127843,  1.0014129 , ...,  0.86045855,
        -1.18065207,  0.43771214],
       [-1.23323809,  0.13193628, -1.22945086, ..., -1.3635904 ,
        -1.53043585,  0.27386311],
       ...,
       [-0.34730603, -1.42104125, -0.41214237, ..., -0.915901  ,
        -0.95004241, -0.81478767],
       [ 0.60914657, -0.13448362,  0.69977731, ...,  0.87695632,
        -0.23654541,  1.13617115],
       [-0.62995918, -1.072646  , -0.56833176, ..., -0.81451473,
        -0.30309719,  0.99437872]])

In [1556]:
y_train

380    B
168    M
97     B
51     B
396    B
      ..
566    M
223    M
287    B
283    M
145    B
Name: diagnosis, Length: 455, dtype: object

In [1557]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [1558]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [1559]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [1560]:
X_train_tensor.shape

torch.Size([455, 30])

In [1561]:
y_train_tensor.shape

torch.Size([455])

In [1562]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [1563]:
learning_rate = 0.1
epochs = 25

In [1564]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.821605043478876
Epoch: 2, Loss: 3.7076241666142513
Epoch: 3, Loss: 3.5857750121573613
Epoch: 4, Loss: 3.459351894876602
Epoch: 5, Loss: 3.3293396573697605
Epoch: 6, Loss: 3.1949733925727335
Epoch: 7, Loss: 3.05438754407397
Epoch: 8, Loss: 2.9061847235855978
Epoch: 9, Loss: 2.7532081433810314
Epoch: 10, Loss: 2.601415702270757
Epoch: 11, Loss: 2.443694255569639
Epoch: 12, Loss: 2.273091698632756
Epoch: 13, Loss: 2.1055115000724127
Epoch: 14, Loss: 1.9435325877470528
Epoch: 15, Loss: 1.7812529959401429
Epoch: 16, Loss: 1.6186042719633957
Epoch: 17, Loss: 1.4664251225123337
Epoch: 18, Loss: 1.324316391646521
Epoch: 19, Loss: 1.1983108253486905
Epoch: 20, Loss: 1.0903094320464681
Epoch: 21, Loss: 1.0013723835069421
Epoch: 22, Loss: 0.9312645805166091
Epoch: 23, Loss: 0.8782681744911688
Epoch: 24, Loss: 0.8394857628606979
Epoch: 25, Loss: 0.8115427525417233

In [1565]:
model.bias

tensor([-0.0873], dtype=torch.float64, requires_grad=True)

In [1566]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6549707651138306

# Update NN using nn module

In [1567]:
import torch.nn as nn

In [1568]:
class Model(nn.Module):

  def __init__(self, num_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [1569]:
features = torch.rand(10, 5)

model = Model(features.shape[1])
model(features)

tensor([[0.4220],
        [0.4241],
        [0.3960],
        [0.3945],
        [0.4120],
        [0.4027],
        [0.4524],
        [0.4309],
        [0.4058],
        [0.4400]], grad_fn=<SigmoidBackward0>)

In [1570]:
model.linear , model.linear.weight , model.linear.bias

(Linear(in_features=5, out_features=1, bias=True),
 Parameter containing:
 tensor([[-0.4056, -0.1018, -0.3166,  0.0471, -0.3581]], requires_grad=True),
 Parameter containing:
 tensor([0.2276], requires_grad=True))

In [1571]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [1572]:
from torchinfo import summary

summary(model, input_size=features.shape)

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [1573]:
class Model2(nn.Module):

  def __init__(self, num_features):
    super(Model2, self).__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [1574]:
features2 = torch.rand(10, 5)

model2 = Model2(features.shape[1])
model2(features2)

tensor([[0.5606],
        [0.5479],
        [0.5395],
        [0.5507],
        [0.5715],
        [0.5430],
        [0.5353],
        [0.5435],
        [0.5558],
        [0.5428]], grad_fn=<SigmoidBackward0>)

In [1575]:
print(model2.linear1 , model2.linear1.weight , model2.linear1.bias)
print(model2.linear2 , model2.linear2.weight , model2.linear2.bias)

Linear(in_features=5, out_features=3, bias=True) Parameter containing:
tensor([[ 0.3453,  0.2645,  0.1941,  0.1306, -0.4065],
        [-0.0949, -0.2253,  0.2884, -0.0674, -0.2059],
        [-0.0903,  0.3388, -0.1131, -0.2605,  0.3282]], requires_grad=True) Parameter containing:
tensor([-0.3215, -0.1887,  0.3872], requires_grad=True)
Linear(in_features=3, out_features=1, bias=True) Parameter containing:
tensor([[-0.1469,  0.5101, -0.2716]], requires_grad=True) Parameter containing:
tensor([0.3388], requires_grad=True)

In [1576]:
summary(model2, input_size=features2.shape)

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# using sequencial

In [1577]:
class Model3(nn.Module):

  def __init__(self, num_features):
    super(Model3, self).__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

features3 = torch.rand(10, 5)

model3 = Model3(features.shape[1])
model3(features3)

summary(model3, input_size=features3.shape)

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model3                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# Updation usind nn on prev Manual NN

In [1578]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super(MySimpleNN, self).__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [1579]:
learning_rate = 0.1
epochs = 25

In [1580]:
loss_function = nn.BCELoss()
# create model
model4 = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model4.parameters(), lr=learning_rate)

y_train_tensor = y_train_tensor.float()
X_train_tensor = X_train_tensor.float()
X_test_tensor = X_test_tensor.float()
# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model4(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # zero gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.919502854347229
Epoch: 2, Loss: 0.6406253576278687
Epoch: 3, Loss: 0.5047450661659241
Epoch: 4, Loss: 0.4295554757118225
Epoch: 5, Loss: 0.3808786869049072
Epoch: 6, Loss: 0.34623822569847107
Epoch: 7, Loss: 0.3200378119945526
Epoch: 8, Loss: 0.29935914278030396
Epoch: 9, Loss: 0.28251731395721436
Epoch: 10, Loss: 0.26846545934677124
Epoch: 11, Loss: 0.2565155327320099
Epoch: 12, Loss: 0.2461949586868286
Epoch: 13, Loss: 0.23716740310192108
Epoch: 14, Loss: 0.22918619215488434
Epoch: 15, Loss: 0.22206588089466095
Epoch: 16, Loss: 0.21566402912139893
Epoch: 17, Loss: 0.20986928045749664
Epoch: 18, Loss: 0.2045930027961731
Epoch: 19, Loss: 0.1997637003660202
Epoch: 20, Loss: 0.19532310962677002
Epoch: 21, Loss: 0.19122298061847687
Epoch: 22, Loss: 0.18742305040359497
Epoch: 23, Loss: 0.1838895082473755
Epoch: 24, Loss: 0.18059349060058594
Epoch: 25, Loss: 0.17751044034957886

In [1581]:
model4.linear.bias

Parameter containing:
tensor([-0.0548], requires_grad=True)

In [1582]:
# model evaluation
with torch.no_grad():
  y_pred = model4(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5818713307380676

In [1583]:
from sklearn.datasets import make_classification
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [1584]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [1585]:
class CustomDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return self.X.shape[0]
        # return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [1586]:
dataset = CustomDataset(X,y)
len(dataset),dataset[1]

(10, (array([-1.14021544, -0.83879234]), np.int64(0)))

In [1587]:
for batch_features,batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("_" * 10)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
__________
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
__________
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
__________
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
__________
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
__________

#  more updation

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [1589]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [1590]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]

In [1591]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [1598]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [1599]:
learning_rate = 0.1
epochs = 25

In [1601]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [1602]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.27749961614608765
Epoch: 2, Loss: 0.10456852614879608
Epoch: 3, Loss: 0.1363479346036911
Epoch: 4, Loss: 0.22957761585712433
Epoch: 5, Loss: 0.10990109294652939
Epoch: 6, Loss: 0.13075673580169678
Epoch: 7, Loss: 0.22403429448604584
Epoch: 8, Loss: 0.047130338847637177
Epoch: 9, Loss: 0.1052340418100357
Epoch: 10, Loss: 0.10746794193983078
Epoch: 11, Loss: 0.14751063287258148
Epoch: 12, Loss: 0.011129537597298622
Epoch: 13, Loss: 0.017313245683908463
Epoch: 14, Loss: 0.008528766222298145
Epoch: 15, Loss: 0.087002232670784
Epoch: 16, Loss: 0.0245333444327116
Epoch: 17, Loss: 0.0888567566871643
Epoch: 18, Loss: 0.0020228021312505007
Epoch: 19, Loss: 0.11580325663089752
Epoch: 20, Loss: 0.05578257516026497
Epoch: 21, Loss: 0.030717281624674797
Epoch: 22, Loss: 0.009097849950194359
Epoch: 23, Loss: 0.04731154069304466
Epoch: 24, Loss: 0.046255555003881454
Epoch: 25, Loss: 0.017703937366604805

In [1596]:
# create model
model5 = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model5.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [1603]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9922